### ISSUE TITLE
mozilla.components.feature.media.service.MediaSessionServiceDelegate$onCreate Crash in [@ java.lang.IllegalStateException: at android.os.Parcel.createExceptionOrNull(Parcel.java)] Too many receivers, total of 1000, registered for pid

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/android-components#12111]
https://bugzilla.mozilla.org/show_bug.cgi?id=1768053

Crash report: https://crash-stats.mozilla.org/report/index/f098bbbb-7fa6-46c5-b682-b13a00220505

Looks like a bug related to `mozilla.components.feature.media.service.MediaSessionServiceDelegate$onCreate`

Java stack trace:
```
java.lang.IllegalStateException: Too many receivers, total of 1000, registered for pid: 31989, callerPackage: org.mozilla.fenix
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2433)
	at android.os.Parcel.createException(Parcel.java:2409)
	at android.os.Parcel.readException(Parcel.java:2392)
	at android.os.Parcel.readException(Parcel.java:2334)
	at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:5530)
	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1769)
	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1723)
	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1711)
	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:724)
	at mozilla.components.feature.media.service.MediaSessionServiceDelegate$onCreate$1$invokeSuspend$$inlined$collect$1.emit(Collect.kt:25)
	at mozilla.components.support.ktx.kotlinx.coroutines.flow.FlowKt$ifChanged$$inlined$filter$1$2.emit(Collect.kt:9)
	at mozilla.components.feature.media.service.MediaSessionServiceDelegate$onCreate$1$invokeSuspend$$inlined$map$1$2.emit(Collect.kt:5)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt.emitAllImpl$FlowKt__ChannelsKt(Channels.kt:14)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(Channels.kt:1)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:4)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7839)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.ActivityManagerService.registerReceiverWithFeature(ActivityManagerService.java:12463)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2209)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2498)
	at android.os.Binder.execTransactInternal(Binder.java:1179)
	at android.os.Binder.execTransact(Binder.java:1143)
```

**Comment by csadilek** [comment]
This should have been fixed by https://github.com/mozilla-mobile/android-components/pull/12073. We're also tracking it in Fenix: https://github.com/mozilla-mobile/fenix/issues/25011

@Amejia481 @rocketsroger Did the fix help?

**Comment by rocketsroger** [comment]
Fixed was in but looks like it is still happening.

**Comment by Amejia481** [comment]
Based on the [Sentry nightly](https://sentry.io/organizations/mozilla/issues/3182273882/?project=6295546&query=is%3Aunresolved+Too+many+receivers) report the trend is going down

<img width="341" alt="image" src="https://user-images.githubusercontent.com/773158/167025758-7811607d-64f5-40cb-bdcd-90ce0fe03785.png">

I'm trying to pinpoint the exact AC version to make sure.
<img width="391" alt="image" src="https://user-images.githubusercontent.com/773158/167025954-f9c0fdef-83db-4d81-b9bb-a48ac5484180.png">

**Comment by Amejia481** [comment]
Yes, the issue it's still present the fixed was introduced on AC `101.0.20220428190151`

**Comment by rocketsroger** [comment]
I see an issue with the fix.  Here's a PR to fix it https://github.com/mozilla-mobile/android-components/pull/12113

**Comment by rocketsroger** [comment]
Confirmed that looking at recent Sentry (or lack of) reports, this crash has been fixed. Closing.

**Comment by cpeterso** [comment]
@rocketsroger - I still see some `java.lang.IllegalStateException: at android.os.Parcel.createExceptionOrNull(Parcel.java)` crash reports from Fenix Nightly v102.0a1. Are those crashes a different problem?

https://crash-stats.mozilla.org/signature/?signature=java.lang.IllegalStateException%3A%20at%20android.os.Parcel.createExceptionOrNull%28Parcel.java%29&date=%3E%3D2022-04-27T06%3A13%3A00.000Z&date=%3C2022-05-27T06%3A13%3A00.000Z

**Comment by rocketsroger** [comment]
> @rocketsroger - I still see some `java.lang.IllegalStateException: at android.os.Parcel.createExceptionOrNull(Parcel.java)` crash reports from Fenix Nightly v102.0a1. Are those crashes a different problem?
> 
> https://crash-stats.mozilla.org/signature/?signature=java.lang.IllegalStateException%3A%20at%20android.os.Parcel.createExceptionOrNull%28Parcel.java%29&date=%3E%3D2022-04-27T06%3A13%3A00.000Z&date=%3C2022-05-27T06%3A13%3A00.000Z

@cpeterso Yes it looks like they are a different issue.  The issue that I fixed was caused by the `MediaSessionServiceDelegate`.  The new reports from your link seems to be from PWA.  I think a new issue should be created to track that.
