### ISSUE TITLE
Search engine migration: IndexOutOfBoundsException: Index: 0, Size: 0

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#5842]
https://sentry.prod.mozaws.net/operations/fenix-fennec-nightly/issues/7227032/

```
IndexOutOfBoundsException: Index: 0, Size: 0
    at java.util.ArrayList.get(ArrayList.java:437)
    at mozilla.components.browser.search.SearchEngineManager.getProvidedDefaultSearchEngineAsync(SearchEngineManager.kt:9)
    at mozilla.components.browser.search.SearchEngineManager.getDefaultSearchEngineAsync(SearchEngineManager.kt:7)
    at mozilla.components.browser.search.SearchEngineManager$getDefaultSearchEngineAsync$1.invokeSuspend
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:2)
...
(3 additional frame(s) were not displayed)

Index: 0, Size: 0
```

**Comment by pocmo** [comment]
This is not migration related and happens in Fenix Nightly too. Still not often though. Maybe there is a very specific configuration that ends up with no search engines?

https://sentry.prod.mozaws.net/operations/fenix-nightly/issues/6722820

**Comment by pocmo** [comment]
Sentry issue: [FENIX-FENNEC-NIGHTLY-AG](https://sentry.prod.mozaws.net/operations/fenix-fennec-nightly/issues/7288989/)

**Comment by st3fan** [comment]
This is probably a dupe, but this is now a high frequency startup crash on 79b4 and 79b4 - so I am marking it as a blocker.

**Comment by kbrosnan** [comment]
This looks like it was fixed by https://github.com/mozilla-mobile/fenix/issues/11875 as long as we have that on the branch we should be good.

**Comment by codrut-topliceanu** [comment]
https://sentry.prod.mozaws.net/operations/fenix-fennec-beta/issues/8615027
@kbrosnan Seems issue is still present in org.mozilla.firefox_beta-79.0.0-beta.4 should I open another issue for it?

**Comment by pocmo** [comment]
This is a somewhat older build too. 81 is currently on the beta track.
