### ISSUE TITLE
Fennec migration: The Custom Import field from the uBlock Dashboard is not entirely visible

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/android-components#6933]
## Preconditions:
Have uBlock Origin added to Fennec and pages added to the Custom Import field.
## Steps to reproduce
1. Replace Fennec with Fenix;
2. Go to uBlock Origin Options -> Filter lists -> Custom;
3. Tap the "Import" checkbox;
4. Observe the editable field;
### Expected behavior
The Custom Import field is visible.
### Actual behavior
The Custom Import field is not entirely visible.
### Notes:
This is also reproducible when there are no other pages added to the Custom list.
![20200511_121418](https://user-images.githubusercontent.com/48799384/81545150-1fb15100-9381-11ea-8d20-a4a0df56a7de.gif)

### Device information
* Android device: Motorola Moto G6 (Android 8);
* Fenix version: Nightly migration build 200511.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-5921)

**Comment by pocmo** [comment]
CC @csadilek @Amejia481

**Comment by Amejia481** [comment]
For some reason, when we are in an extension setting page the toolbar is not auto hiding when scrolling this is not the case if the toolbar is on the top see this [video](https://drive.google.com/file/d/1xgHK3jvJvnFNNYg7NT8c7H_sRCwWob7O/view?usp=sharing)

**Comment by Amejia481** [comment]
I think we are having some issue with the bottom toolbar animation. I'm not sure if it's because the navigation on `UBlock` origin is based on `iframes` and causing GV to not giving us the right flags. I chatted with @Mugurell about it. As he mentioned our [actual implementation ](https://github.com/mozilla-mobile/android-components/blob/1d32ae0fa1496a8c04a9fc06e9217b2ecc150ff0/components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/behavior/BrowserToolbarBottomBehavior.kt#L84) indicates that we only animate if we get `INPUT_RESULT_HANDLED`
 from GV but right now GV is sending us `INPUT_RESULT_HANDLED_CONTENT` or 
`INPUT_RESULT_UNHANDLED` causing that we do not animate and the bottom part of the page is not getting shown

**Comment by Amejia481** [comment]
There is a similar Bugzilla bug opened https://bugzilla.mozilla.org/show_bug.cgi?id=1633322, I commented to mention that same issue is happening for Ublock internal setting pages

**Comment by hwinnemoe** [comment]
BZ-1633322 has been fixed.

**Comment by Mugurell** [comment]
And with ^^ being merged in AC we can check if the problem is fixed in tomorrow's Fenix Nightly.

**Comment by Mugurell** [comment]
Passing to @ebalazs-sv for testing if the initial issue is now fixed.

**Comment by ebalazs-sv** [comment]
This issue is still reproducible on Nightly 200828 GV 81.0a1 from 8/28 with Pixel 2 (Android 9) and Motorola Moto G6 (Android 8).

![20200828_170428](https://user-images.githubusercontent.com/48799384/91577073-e234fb80-e950-11ea-9d28-41ea66b70b33.gif)

**Comment by smhmore** [comment]
A most frustrating obstacle, affecting many government websites where Submit or Continue or Next buttons are always on the very bottom.

**Comment by Mugurell** [comment]
> A most frustrating obstacle, affecting many government websites where Submit or Continue or Next buttons are always on the very bottom.

Can you please open a new issue here - https://github.com/mozilla-mobile/fenix (I think you encounter this on Fenix and there it would get more visibility) with examples where this is happening?

**Comment by Mugurell** [comment]
I'm seeing in RB a different behavior in regards to whether the toolbar is shown or not depending on from where uBlock's settings are accessed:
![DoAddonsNeedToolbar](https://user-images.githubusercontent.com/11428869/91866077-c5fbcc00-ec7a-11ea-9a7e-283407774eab.gif)
[video](https://drive.google.com/file/d/1b7eIub1JLXyn4Zvw9qZxJPyPywPiCJJW/view?usp=sharing)

So I'm wondering, should we show the toolbar when users access the addons configurations pages?
I don't think it presents any useful information to the user in that context and even more, some of the menu options, like "share" would not bring the expected result (the shared tab is not for an internet resource that can be accessed by everyone that's shared but a local webpage).
@Amejia481 @AmyYLee any opinions on this?

**Comment by Mugurell** [comment]
Thank you!
Makes sense, I'm new to this part and saw differences between how different addons' details/settings screens are opened.

**Comment by Mugurell** [comment]
Seems like the toolbar should've been animated away so that the entire page is available but this is not happening because GV returns `INPUT_RESULT_HANDLED_CONTENT` signaling that the scroll is handled by the page and not GV.

Not sure if this is a webcompat issue that should be resolved by the developers of uBlock or an issue in GV so I opened https://bugzilla.mozilla.org/show_bug.cgi?id=1662823

**Comment by Poopooracoocoo** [comment]
> Seems like the toolbar should've been animated away so that the entire page is available but this is not happening because GV returns `INPUT_RESULT_HANDLED_CONTENT` signaling that the scroll is handled by the page and not GV.
> 
> Not sure if this is a webcompat issue that should be resolved by the developers of uBlock or an issue in GV so I opened https://bugzilla.mozilla.org/show_bug.cgi?id=1662823

@Mugurell that bug you linked was fixed but the toolbar still doesn't auto hide in fenix :/ uBO worked around fenix's bug btw

**Comment by Mugurell** [comment]
This seems fixed. Closing as such.
